require:
  - rubocop-rake
  - rubocop-rspec

# Ensures the Exclude list is merged instead of overwritten when defining separate configurations.
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - "demo/**/*"
    - "spec/mock_files/**/*"
    - "Gemfile"
    - "Rakefile"

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 50 # Default block length for most files
  Exclude:
    - "Rakefile"

# Custom settings for .gemspec files
Metrics/BlockLength:
  Max: 100 # Higher block length limit for .gemspec
  Include:
    - "*.gemspec"

Naming/FileName:
  Exclude:
    - lib/jekyll-sketchviz.rb

RSpec/MultipleExpectations:
  Max: 3 # Relaxed rule: Allow up to 3 expectations per example
  Exclude:
    - "spec/**/*" # Optionally exclude specific test files

RSpec/ExampleLength:
  Max: 8 # Relaxed rule: Allow examples up to 8 lines long
  Exclude:
    - "spec/**/*" # Optionally exclude specific test files
